### PR TITLE
Kodeco Reskin

### PR DESCRIPTION
**Pull request by RobertoMachorro**
This pull request includes changes that rebrand Emitron from Razeware to Kodeco. Summary:

* Replaced RayWenderlich images with Kodeco.
* Added Kodeco based icon sets (for Live, Dev & Beta).
*  Migrated application fonts to Relative family of fonts.
* Updated misc views and revamped Splash screen.
* Adjusted background colors and misc views (controls) to official Figma spec for Dark mode. _Dark Mode is currently the only mode supported for now._
* Library, Network Error, Login, Logout, etc views changed as per Abby's requests.
* Buttons in all views where changed to Kodeco style.

In addition, after Xcode and SwiftLint updates it was necessary to update some rules to exclude _large_tuple_ and _type_name_ checks.

### CODE REVIEW

**Review by sammyd — APPROVED** [review]
:+1: Great—thanks for this Roberto! I've not tested it locally, but if you're ready, go ahead and merge it, and we'll see whether it manages to send out a test flight build...

Nice work!

**Comment by RobertoMachorro** [comment]
> 👍 Great—thanks for this Roberto! I've not tested it locally, but if you're ready, go ahead and merge it, and we'll see whether it manages to send out a test flight build...

I don't have permissions to merge...?

**Comment by sammyd** [comment]
Oh, apologies—I assumed that you would have. I'll merge now.

**Comment by RobertoMachorro** [comment]
Looks good! I'm going to go ahead and delete my branch.

**Pull request merged**
