### PR TITLE
Fix for Issue 567

### PR DESCRIPTION
**Pull request by JessyCatterwaul**
https://github.com/razeware/emitron-iOS/issues/567

### CODE REVIEW

**Comment by JessyCatterwaul** [comment]
I haven't worked with Emitron in a long time. Is this failure expected?

**Comment by sammyd** [comment]
I don't know of a reason why the tests would fail. The only issue might be around timeouts for the async tests. Taking a look at the output will give an indication of which tests are failing, which might help narrow down what the problem is.

**Comment by JessyCatterwaul** [comment]
Passed here: https://github.com/razeware/emitron-iOS/pull/593
How do I kick off the tests again? I feel pretty certain I don't need to make any code changes.

**Comment by sammyd** [comment]
image

Details. Then "re-run jobs > Re-run all jobs"

**Comment by JessyCatterwaul** [comment]
Again, it failed.
Once more, and it did not fail.

That's good enough for me for now, but I'd prefer it to be more deterministic… 😑

**Comment by sammyd** [comment]
I think the solution is to either come up with a better way to test the async code, or just extend the timeouts. Not sure why they take so long. I guess shared Macs being quite slow.

**Review by 0xTim — APPROVED** [review]
This LGTM. With regards to the tests I'm hoping that some of the a/a stuff will help that but yes the tests are causing lots off issues with CI and PRs. We could investigate wrapping the tests that need to wait with helpers to automatically retry or remove the source of asynchronicity and replacing it with something we can stub out in tests to control better

**Pull request merged**
