### PR TITLE
Content list view

### PR DESCRIPTION
**Pull request by JessyCatterwaul**
I cleaned up and organized ContentListView while preparing to fix (not currently fixing though) https://github.com/razeware/emitron-iOS/issues/598.

### CODE REVIEW

**Comment by 0xTim** [comment]
@JessyCatterwaul looks like there are some merge conflicts to resolve (sorry for the spam 😅)

**Comment by JessyCatterwaul** [comment]
@0xTim Rebased!

**Comment by 0xTim** [comment]
@JessyCatterwaul does this fix #598 or is it just in preparation of the fix?

**Review by 0xTim — DISMISSED** [review]

**Comment by JessyCatterwaul** [comment]
@0xTim Sadly, I haven't fixed #598 yet. 😿
This is just some cleanup which will reduce distraction while dealing with that issue.

**Comment by 0xTim** [comment]
Cool, I'll unlink the issue

**Review by 0xTim — APPROVED** [review]

**Pull request merged**
