### PR TITLE
App illustrations

### LINKED ISSUE #492: General: Update Illustrations
This is a task for the design team. 

When I have time I'll send you some new illustrations to apply through out the app!

### PR DESCRIPTION
**Pull request by VegetarianZombie**
This pull request updates all the illustrations used throughout the app in both regular and dark mode. It also correctly displays the "empty bookmarks" icon instead of the "empty tutorials" icon.  This PR resolves the following issue: https://github.com/razeware/emitron-iOS/issues/492

### CODE REVIEW

**Comment by VegetarianZombie** [comment]
@luke-freeman Here are the screenshots. Please review and send any feedback. Thanks!

1_dark-mode_preview
1_light-mode_preview
2_dark-mode_preview
2_light-mode_preview
3_dark-mode_preview
3_light-mode_preview
4_dark-mode_preview
4_light-mode_preview
5_dark-mode_preview
5_light-mode_preview
6_dark-mode_preview
6_light-mode_preview
7_dark-mode_preview
7_light-mode_preview
8_dark-mode_preview
8_light-mode_preview
s!

**Comment by VegetarianZombie** [comment]
@0xTim I've updated this pull request. When you have a moment, would you take a look at MyTutorialsView.swift at line 175. it's a little clunky - using a ternary inside a ternary. Any thoughts on a different approach?

**Comment by luke-freeman** [comment]
@VegetarianZombie 

Nice work!

My only comment would be that the Downloads, My Tutorials and Bookmarks illustrations could do with some padding from the top. But other than that it's excellent.

**Comment by JessyCatterwaul** [comment]
@VegetarianZombie I made one more commit for `MyTutorialsView`. Thanks for pointing that out—there was actually unused logic in the file. Should be good now. Thanks!

**Review by JessyCatterwaul — APPROVED** [review]

**Pull request merged**
