### PR TITLE
Miscellaneous cleanup

### PR DESCRIPTION
**Pull request by JessyCatterwaul**
I cleaned up some files with common code issues that could be improved, and caught a couple unique issues as well.

### CODE REVIEW

**Comment by JessyCatterwaul** [comment]
This is getting errors. Fastlane apparently is running behind Swift 5.4. What do we do about that?

**Comment by 0xTim** [comment]
@JessyCatterwaul looks like there are some merge conflicts to resolve

**Comment by JessyCatterwaul** [comment]
@0xTim I fixed the conflict, but we've still got the Swift 5.4 problem.

This requires Swift 5.4.
One of my later PRs will require Swift 5.5. (I'm not using iOS 15 features though.)

What do we do?

**Comment by 0xTim** [comment]
I'm happy to bump the required Swift version to 5.4. For 5.5 we'll obviously need to wait for Xcode 13 to be released but I don't see an issue with that as long as it's still iOS 14 compatible. (I guess whether we drop iOS 14 is dependant on any critical SwiftUI fixes and async/await being backported)

**Comment by 0xTim** [comment]
@JessyCatterwaul looks like there are build failures instead of flaky tests

**Comment by JessyCatterwaul** [comment]
@0xTim Xcode 12.5 is the release that first supported Swift 5.4, but we've got this going on:

Screen Shot 2021-09-07 at 7 42 46 AM

**Comment by 0xTim** [comment]
@JessyCatterwaul we can update it here https://github.com/razeware/emitron-iOS/blob/development/.github/workflows/run_tests.yml#L13, feel free to bump to 12.5

**Comment by JessyCatterwaul** [comment]
@0xTim Well, [the simplest thing](https://github.com/Catterwaul/emitron-iOS/commit/9818bba143ca5f34f372017676e944f960471b7f) didn't work.

https://docs.fastlane.tools/actions/xcode_select/ doesn't tell me how to check to see what we actually have available. Do you know how that's done?

**Comment by sammyd** [comment]
https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/

**Comment by sammyd** [comment]
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md

**Comment by sammyd** [comment]
seem to remember this was the problem with 12.5—it's only supported on macOS 11, and that wasn't generally available until recently.

**Comment by JessyCatterwaul** [comment]
Thanks a bunch, @sammyd!

Given that Xcode 12.5.1 is the default on macOS 11 (per your last link), is it appropriate that I just deleted `xcode_select`? As you can see, the tests pass now, with that change: https://github.com/Catterwaul/emitron-iOS/commit/2448c4ad513690dbcd78bfd540e12f31837aad73

**Comment by sammyd** [comment]
I would tend to keep the Xcode-select line so that we can guarantee what version it's running on (rather than at some point, Xcode 13 becoming the default). It's annoying to remember to keep it up to date, but I think is worth it in the long run.

**Comment by JessyCatterwaul** [comment]
Okay! We're switched back to a hard-coded Xcode 12.5.1 (likely the last of the 12 cycle).

**Review by 0xTim — APPROVED** [review]

**Pull request merged**
