### PR TITLE
Light mode style updates

### LINKED ISSUE #511: Global: Light Mode Style Updates
Update the light mode version of the app to match the website. 

- Remove all instances of the grey background
- Add drop shadow to cards and search box
- Adjust drop shadow of the bottom navigation

It should look similar to this: 

Library (Light Mode)

You can find full designs for light mode here

https://www.figma.com/file/LCwFKA0AmG9EcOQPBamGAb/Emitron-iOS?node-id=0%3A2533

### PR DESCRIPTION
**Pull request by VegetarianZombie**
This pull request changes some of the UI elements per Luke's Figma design as requested on issue 511:

https://github.com/razeware/emitron-iOS/issues/511

Simulator Screen Shot - iPhone 13 - 2021-10-29 at 15 46 29
Simulator Screen Shot - iPhone 13 - 2021-10-29 at 15 46 37
Simulator Screen Shot - iPhone 13 - 2021-10-29 at 15 46 48
Simulator Screen Shot - iPhone 13 - 2021-10-29 at 15 51 52
Simulator Screen Shot - iPhone 13 - 2021-10-29 at 15 51 58

### CODE REVIEW

**Comment by JessyCatterwaul** [comment]
Hey @VegetarianZombie!

I'm concerned about the removal of the lines from `TabNavView`—I put them in because of #598. Does iOS 15.1 render them properly without, now?

I tried to check for myself, but can't get the project to compile. I suspect it's due to an unresolved merge conflict in the `Package.resolved` file?

**Comment by luke-freeman** [comment]
@VegetarianZombie 

Looks good from what I can see. 

Just one question:

- The content seems to have different padding left and right to the title (it should match the title padding)

**Comment by luke-freeman** [comment]
@VegetarianZombie 

Any update on the final comment of this?

**Comment by VegetarianZombie** [comment]
@luke-freeman This is a bug that exists in the current version of the app. I'll create an issue for it and tag it as a good first issue.

**Comment by VegetarianZombie** [comment]
Hey @JessyCatterwaul, I added back that change you made so it appears correctly on iOS 15. Ready to review.

**Comment by JessyCatterwaul** [comment]
@VegetarianZombie I'm merging this now—thanks!
However, I removed the `NavigationConfigurator` file, which was not being used here. Please let me know if it will be useful elsewhere. I don't recall if I've ever worked with it before.

**Pull request merged**
