### PR TITLE
Issue 494: Add swipe between tabs on My Tutorials view

### PR DESCRIPTION
**Pull request by heathermh**
Added ability to swipe left and right between In Progress/Completed/Bookmarks on My Tutorials view.

[My Tutorials: Swipe to switch sections #494](https://github.com/razeware/emitron-iOS/issues/494)

### CODE REVIEW

**Review by 0xTim — DISMISSED** [review]
This looks good to me - could you attach a video of it working in the simulator for @luke-freeman to approve?

**Comment by heathermh** [comment]
> This looks good to me - could you attach a video of it working in the simulator for @luke-freeman to approve?

Video of swipe:

https://user-images.githubusercontent.com/1638675/125527829-219cb949-50b3-4699-a418-83606653fbf6.mov

**Comment by luke-freeman** [comment]
@0xTim @heathermh 

Looks great!

**Comment by 0xTim** [comment]
@heathermh could you update your branch to fix the conflicts and then we can merge this in!

**Comment by heathermh** [comment]
@0xTim good to go!

**Comment by 0xTim** [comment]
@heathermh do you want to try pulling in the latest code from main to increase the timeouts and if that doesn't work increase the timeouts of the ones that are failing manually? As soon as CI is green we can merge!

**Comment by heathermh** [comment]
@0xTim I updated heathermh/emitron-iOS, but need approval to see if CI will work.

**Review by 0xTim — APPROVED** [review]
LGTM!

**Pull request merged**
