### PR TITLE
Issue 536: Replace ActivityIndicator with ProgressView

### LINKED ISSUE #536: Replace ActivityIndicator with ProgressView
Use new ProgressView instead of custom activity indicator after iOS13 is not supported. 

https://developer.apple.com/documentation/swiftui/progressview

### PR DESCRIPTION
**Pull request by riana-soumi**
This pull request replaces UIActivityIndicatorView with SwiftUI ProgressView.
It should be merged after #581 is merged since ProgressView is only compatible with iOS 14.0+

Closes #536

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by 0xTim** [comment]
@ria-heikkila #581 has now been merged - could you fix the conflicts and we can get this merged!

**Comment by riana-soumi** [comment]
@0xTim  done!

**Comment by 0xTim** [comment]
@ria-heikkila do you want to try pulling in the latest code from main to increase the timeouts and if that doesn't work increase the timeouts of the ones that are failing manually? As soon as CI is green we can merge!

**Comment by riana-soumi** [comment]
@0xTim 
Sorry, I am not sure why but I was unable to pull the latest changes from development, so I just created the new PR for this issue, it is #594
Please check it out

**Pull request closed without merging**
