### PR TITLE
Set filter to always be in uppercase (#463)

### PR DESCRIPTION
**Pull request by VegetarianZombie**
Currently, in development, when the library first appears, the header strings have the first letter capitalized but the reset of the string in lowercase. Here's what it looks like on start:

Screen Shot 2020-09-20 at 1 17 58 PM

Then when the content is loaded, the title case changes to uppercase as shown here:

Screen Shot 2020-09-20 at 1 18 16 PM

I've set the text to always be uppercased now.

### CODE REVIEW

**Comment by sammyd** [comment]
I'm pretty sure that it's supposed to be sentence-cased (as it is on start) not uppercased. Pretty sure that we don't use all-uppercase for any messaging like this.

@luke-freeman can you confirm for me please?

**Comment by sammyd** [comment]
@VegetarianZombie I've merged a lot of Jessy's commits to `development` today, so there's bound to be merge conflicts. Please can you resolve these, either by merging development into this branch, or rebasing this on top of development. Thanks!

(once Luke has confirmed the correct typography that is (= )

**Comment by sammyd** [comment]
This fixes #463

**Comment by VegetarianZombie** [comment]
Will do!

**Comment by luke-freeman** [comment]
@VegetarianZombie It should be in sentence case!

**Comment by 0xTim** [comment]
Thanks for the PR @VegetarianZombie - however closing as per the comments

**Comment by VegetarianZombie** [comment]
I'm confused - why was this closed? I need to update my PR as the casing bug is still present in the live version.

**Comment by 0xTim** [comment]
@VegetarianZombie apologies I misread the initial description! I've opened it back up

In terms of fixing the bug - it should _always_ be sentence case and never all caps

**Comment by VegetarianZombie** [comment]
Hi Tim, 

Thanks for re-opening up the PR. This turns about to be a result of iOS 14. It's a new styling feature. Anything put inside a list's section header will now be in all upper case. I had add an attribute to check the OS version in order to set the appropriate case.

Here's what it looks like now:

Screen Shot 2020-10-02 at 1 42 18 PM

@sammyd Ready for review.

**Review by sammyd — APPROVED** [review]
:+1:

**Pull request merged**
