### PR TITLE
Ios13 removal

### LINKED ISSUE #545: Refactor from UIKit App Delegate life-cycle to SwiftUI life-cycle
Removed AppDelegate & SceneDelegate refactor to use SwiftUI life-cycle.  After iOS13 is dropped.

### PR DESCRIPTION
**Pull request by VegetarianZombie**
This PR does a major refactor of the Emitron, removing iOS 13 support. The major point of this refactor moves the vast majority of the App Delegate to the EmitronApp struct. From there, the central objects that comprise Emitron are passed into the app by way of environment variables. This means each SwiftUI view is updated to use environment variables and some classes were updated to take in objects versus calling a singleton property.

The PR also removes if directives for iOS 13 since the minimal assumption is iOS 14. Previews and tests were also updated to use this new structure. 

This is a pretty major refactor with a lot of files changed. I imagine it's going to take some time for this to be reviewed. The best place to start is the new EmitronApp struct and work from there.

### CODE REVIEW

**Comment by VegetarianZombie** [comment]
Note - do you want me to solve the merge conflict before review?

**Comment by 0xTim** [comment]
@VegetarianZombie If you could that would be great. Will avoid having to re-review anything also the resolution anyway

**Comment by 0xTim** [comment]
@VegetarianZombie is this good to go?

**Comment by byaruhaf** [comment]
@VegetarianZombie  seems the removal of the line below causes a color inconsistency when logging into the app

`window.rootViewController?.view.backgroundColor = .backgroundColor`

| Light | Dark |
|:-------------------------:|:-------------------------:
|Light  |  Dark | 

A possible solution is a `ZStack` in the EmitronApp struct body property. 

```swift
  var body: some Scene {
    WindowGroup {
      ZStack {
        Rectangle()
          .fill(Color.backgroundColor)
          .edgesIgnoringSafeArea(.all)
        MainView()
          .environmentObject(sessionController)
          .environmentObject(dataManager)
          .environmentObject(downloadService)
          .environmentObject(iconManager)
          .environmentObject(messageBus)
          .environmentObject(persistenceStore)
          .environmentObject(guardpost)
          .environmentObject(settingsManager)
      }
    }
  }
```

**Review by 0xTim — CHANGES_REQUESTED** [review]
This all LGTM we just need to update the login screen as per @byaruhaf's comment

**Comment by VegetarianZombie** [comment]
I'm looking at this today. I'll see what I can do

**Comment by VegetarianZombie** [comment]
I've made some changes per @byaruhaf (Thanks for finding it, Franklin!) - I put the changes on the screens versus the EmitronApp and updated all the view previews. That way, we avoid any potential side effects and the previews show a correctly rendered dark mode.

**Comment by VegetarianZombie** [comment]
Ready for you @0xTim

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
