### PR TITLE
Replaced colorScheme with preferredColorScheme

### PR DESCRIPTION
**Pull request by byaruhaf**
[colorScheme(_:)](https://developer.apple.com/documentation/swiftui/view/colorscheme(_:)) is Deprecated recommendation is to use [preferredColorScheme(_:) ](https://developer.apple.com/documentation/swiftui/view/preferredcolorscheme(_:)) instead.

Signed-off-by: Franklin Byaruhanga <byaruhaf@appbantu.com>

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
LGTM

**Comment by 0xTim** [comment]
@byaruhaf I think we need to up the timeouts

**Comment by byaruhaf** [comment]
Hi, @0xTim the test that failed seen below has no timers and I see no logic in the fail test in relation to the change. 

Going to test again and open a new PR

```swift
  func testRequestDownloadURLUpdatesDownloadInCallback() throws {
    let downloadQueueItem = try sampleDownloadQueueItem()
    
    XCTAssertNil(downloadQueueItem.download.remoteURL)
    XCTAssertNil(downloadQueueItem.download.lastValidatedAt)
    XCTAssertEqual(Download.State.pending, downloadQueueItem.download.state)
    
    downloadService.requestDownloadURL(downloadQueueItem)
    
    try database.read { db in
      let download = try Download.fetchOne(db, key: downloadQueueItem.download.id)!
      XCTAssertNotNil(download.remoteURL)
      XCTAssertNotNil(download.lastValidatedAt)
    }
  }
```

**Comment by byaruhaf** [comment]
Hi, @0xTim the test that failed seen below has no timers and I see no logic in the fail test in relation to the change. 

Going to test again and open a new PR

```swift
  func testRequestDownloadURLUpdatesDownloadInCallback() throws {
    let downloadQueueItem = try sampleDownloadQueueItem()
    
    XCTAssertNil(downloadQueueItem.download.remoteURL)
    XCTAssertNil(downloadQueueItem.download.lastValidatedAt)
    XCTAssertEqual(Download.State.pending, downloadQueueItem.download.state)
    
    downloadService.requestDownloadURL(downloadQueueItem)
    
    try database.read { db in
      let download = try Download.fetchOne(db, key: downloadQueueItem.download.id)!
      XCTAssertNotNil(download.remoteURL)
      XCTAssertNotNil(download.lastValidatedAt)
    }
  }
```

**Pull request closed without merging**
