### PR TITLE
Changed the iOS version to 16.0 as per requirements

### PR DESCRIPTION
**Pull request by NikitaShvadlenko**
Fixing a readme issue https://github.com/razeware/emitron-iOS/issues/678
Changed the version from 13.3 to 16.0 in readme, as described in the link and in this pull request: https://github.com/razeware/emitron-iOS/pull/679

Thank you:)

### CODE REVIEW

**Review by sammyd — DISMISSED** [review]
:+1: Thank you!

**Comment by NikitaShvadlenko** [comment]
Hello again :)
What can I do for the checks not to fail?
I see that there is an error with unwrapping Content, but I did not change anything related to Content.

**Comment by NikitaShvadlenko** [comment]
Update: I noticed that all test failures are related to unwrapping Content, so I added guard statements in tests. 
Also there was a problem with ContentAdapter, it was returning nil, but it looks like it was supposed to throw an error (ContentAdapterTest for the wrong content-type request), so I changed it to throw an error. 
__
I am still a bit confused on how the tests were not working on the development branch. 
I would really appreciate your feedback on whether I did the correct thing and an explanation about how the tests were failing (I am really new to git checks).

Thank you <3

**Comment by NikitaShvadlenko** [comment]
Update: I realised that the content was returning as optional, because of the error in the ContentAdapter - it was meant to throw an error instead of returning nil, when the content-type is wrong. 
So I reverted the commit with guard statements in tests and only left the commit with changing the return type in the ContentAdapter.

**Review by sammyd — APPROVED** [review]
:+1: I don't really understand how tests passed on development either, but this seems ok to me :)

Thank you so much!

**Pull request merged**
