### PR TITLE
Delete `self.` when it doesn't disambiguate

### PR DESCRIPTION
**Pull request by JessyCatterwaul**
Per https://github.com/raywenderlich/swift-style-guide:
"Use self only when required by the compiler"

### CODE REVIEW

**Comment by JessyCatterwaul** [comment]
I don't know fastlane yet. How do we get it to work with Swift 5.3? (The tests pass locally in Xcode 12.)

**Comment by 0xTim** [comment]
We'll need to port CI over to 5.3 as well

**Comment by sammyd** [comment]
We can't really update CI to Xcode 12 until it comes out of beta. There is a beta version of 12 available, but (correct me if I'm wrong) we can't upload to testflight until the GM is released?

https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode

It might be worth splitting this into 2 PRs if appropriate—one that addresses all the issues in Swift 5.2, which can be merged, and then another that addresses just the areas that are 5.3 only?

**Comment by 0xTim** [comment]
Correct, we'll need to keep CI on Xcode 11 for now. I think there's value in having an Xcode 12/Swift 5.3 branch though to catch any issues early

**Comment by sammyd** [comment]
I think updating this line:

https://github.com/razeware/emitron-iOS/blob/development/.github/workflows/run_tests.yml#L16

to reference `/Applications/Xcode_12_beta.app` as part of that branch should allow CI to pass. Might also need to change the trigger to run CI—not sure.

Can I leave that with you to wrangle please @0xTim?

**Comment by 0xTim** [comment]
@sammyd yep I'll get it going

**Comment by 0xTim** [comment]
Cool, this is all good, will merge into the new `xcode-12` branch

**Pull request merged**
