### PR TITLE
Pr/564

### PR DESCRIPTION
**Pull request by VegetarianZombie**
Okay, I updated this pull request. I merged the latest from development and added three unit tests for the FilterGroup class. This is good for review.

### CODE REVIEW

**Review by 0xTim — DISMISSED** [review]
Thanks!

**Comment by 0xTim** [comment]
@VegetarianZombie Looks like there are some build failures in some of the tests

**Comment by adesugbaa** [comment]
Thanks. I see the tests.

**Comment by VegetarianZombie** [comment]
Hi @0xTim, I'm trying to push the updated changes to pr/565 but I'm getting a permission denied error. This is what I'm getting:

`Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 12 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (10/10), 802 bytes | 802.00 KiB/s, done.
Total 10 (delta 8), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (8/8), completed with 8 local objects.        
To https://github.com/adesugbaa/emitron-iOS.git
 ! [remote rejected] pr/564 -> development (permission denied)
error: failed to push some refs to 'https://github.com/adesugbaa/emitron-iOS.git'`

Any thoughts?

**Comment by sammyd** [comment]
@VegetarianZombie it's because the remote it is trying to push to is not the `razeware` one, but instead the one from `adesugbaa`. I think you might be able to update your remote, or just ensure that you are pushing to the correct remote.

**Comment by 0xTim** [comment]
Yeah that looks like you have a fork checked out

**Comment by VegetarianZombie** [comment]
Hi Tim, This should be ready now.

**Review by 0xTim — DISMISSED** [review]
LGTM. @JessyCatterwaul any comments?

**Review by JessyCatterwaul — APPROVED** [review]

**Comment by JessyCatterwaul** [comment]
Everything LGTM as well, except for the `XCAssertTrue`s. I added a commit with specialized `Assert`s, and merged. Thanks!

**Pull request merged**
