### PR TITLE
Wifi only download fix

### LINKED ISSUE #544: Setting Downloads(WIFI only), not working.
### Steps to reproduce

- Go to settings Enable Downloads(WIFI only)

- Try to downloads any video courses

### Expected behavior

The download should fail or be queued for the next time WIFI Available

### Actual behavior

The download is successful and the video plays see the video below:

ezgif com-gif-maker (1)

### Environment

* iOS Version:14.2
* raywenderlich.com App Version: 1.0.6
* Device:iPhone 11

### PR DESCRIPTION
**Pull request by VegetarianZombie**
Prevents users from downloading files over cellular when the setting is enabled. Will present a message via. the message bus.

IMG-0785

### CODE REVIEW

**Comment by sammyd** [comment]
Is this ready for review @VegetarianZombie?

**Comment by VegetarianZombie** [comment]
Hi @sammyd - this should be good for review. I'm not sure why it's failing the fastlane build. Is the build failing again?

**Review by sammyd — APPROVED** [review]
:+1: This looks good to me Brian. The issue with the CI is the async tests, again. Tried running it a few times. We should probably slow down the timeout more drastically.

**Review by 0xTim — APPROVED** [review]
LGTM

**Pull request merged**
